### ISSUE TITLE
wireless_debug example web server vue project sources (AEGHB-448)

### ISSUE THREAD

**Issue by cotestatnt** [espressif/esp-now#100]
Would it be possible to obtain the Vue source files with which the web server included in this example was implemented?
It would be really appreciated
Thank you very much!

[wireless_debug](https://github.com/espressif/esp-now/tree/master/examples/wireless_debug/components/web_server)

**Comment by lhespress** [comment]
@cotestatnt Please see te link as follow: 
https://github.com/espressif/esp-now/blob/master/examples/wireless_debug/components/web_server/web_server.c

**Comment by cotestatnt** [comment]
Hi @lhespress 
Thank you for your reply.
Anyway I meant the sources for the webserver's page itself, not for the ESP32 firmware.

Here we have only the [compiled front-end](https://github.com/espressif/esp-now/tree/master/examples/wireless_debug/components/web_server/front), but the Vue sources are missing

**Comment by lhespress** [comment]
@cotestatnt Please reference the attachment file: 
[归档.zip](https://github.com/espressif/esp-now/files/14340524/default.zip)

**Comment by lhespress** [comment]
@cotestatnt Closing this issue since there has been no update on this. Please feel free to reopen if required.
