### ISSUE TITLE
current master example-OTA issue (AEGHB-492)

### ISSUE THREAD

**Issue by Connor-WangK** [espressif/esp-now#102]
OS: macos 14.2 apple-m2
SDK: both 4.4 5.1 5.2
run the example-OTA always fail
<img width="2054" alt="image" src="https://github.com/espressif/esp-now/assets/118349552/a6d6e1d2-041e-452f-8729-f93e9e18160d">

when I try esp-now ver1.0, everything running ok.

**Comment by dspworks-swaroop** [comment]
Any update ?

**Comment by Connor-WangK** [comment]
nothing update...

**Comment by lhespress** [comment]
@andy-danieal Could you check it again on the master branch?

**Comment by andy-danieal** [comment]
We have tested with latest branch getting same issue.

ESP-IDF Version:- ESP-IDF v5.2-beta2-190-g4ecc978bd6
ESPNow Example:- e422fbc6267db141aeb22cdf3703f676b6efe75a

[ota_initiator_log.txt](https://github.com/espressif/esp-now/files/14381930/ota_master_log.txt)
[ota_responder_log.txt](https://github.com/espressif/esp-now/files/14381932/ota_responder_log.txt)
[sdkconfig_initator.txt](https://github.com/espressif/esp-now/files/14381942/sdkconfig_initator.txt)

**Comment by Connor-WangK** [comment]
Just now, I do a test, everything is running ok.
env: macbook air m2,
sdk: 97594d2076cb2a2358062c9848b3491371c89a57 (HEAD -> release/v5.2)
chip: esp32c3

**Comment by lhespress** [comment]
@Connor-WangK Thanks for your feedback, please close the issue if resolved.

**Comment by andy-danieal** [comment]
@Connor-WangK  and @lhespress We have tried many times and also create new setup and update ESP-IDF with latest branch but getting same issue.

env: Ubuntu
sdk: ESP-IDF v5.2-166-ge0944287f3 
chip: esp32s2

**Comment by Connor-WangK** [comment]
maybe you can try with esp32c3, 
I'm no going on a business, can't do any tests with other chips but esp32c3.

**Comment by ScarsFun** [comment]
Tested with esp32c3 and esp32s2. Issue persist.

**Comment by andy-danieal** [comment]
@lhespress , I have tested with esp32s2 with CONFIG_ESPNOW_OTA_RETRANSMISSION_TIMES=2 then works.
