### ISSUE TITLE
ESP32S3的OTA升级错误

### ISSUE THREAD

**Issue by Nepenthes** [espressif/esp-now#105]
你好，关于ESP-NOW SDK，OTA例程无法运行，有个错误，可以帮忙看一下吗;
![353183511a1912979b4b191eb94004e](https://github.com/espressif/esp-now/assets/10671191/861a342c-f232-44e2-9414-bed3bc2b8090)
错误主要在固件接收端，一直报内存释放相关错误；
硬件环境：ESP32-S3-WROOM-1U N16R2;
软件环境：
idf的commit
357290093430e41e7e3338227a61ef5162f2deed (HEAD, tag: v4.4.6)
esp-now的commit
cee3e41d38e61fe8ee4db4568690b6ec11ceaeda (HEAD -> master, origin/master, origin/HEAD)

完整的log文件：
[ota_log_202401161620.zip](https://github.com/espressif/esp-now/files/13947336/ota_log_202401161620.zip)

**Comment by lhespress** [comment]
@Nepenthes Could you check it again on the master and use ESP-IDF tag: 5.1.2

**Comment by lhespress** [comment]
@Nepenthes Closing this issue since there has been no update on this. Please feel free to reopen if required.
