### ISSUE TITLE
Is it possible to send OTA files via UART without internet in ESPNow? (AEGHB-539)

### ISSUE THREAD

**Issue by andy-danieal** [espressif/esp-now#108]
**ESPNow gateway** was connected via UART to the **Ubuntu system** and **many devices** (with different types of firmware) were connected to the gateway to communicate with ESPNow.

*Notes*:- ESPNow gateways have different firmware from other devices.

**Comment by n3b0j5a** [comment]
Yeah, you can do that, you need to develop some kind of protocol to download firmware via UART (to some dedicated or OTA partition), and than send it over via espnow.

**Comment by andy-danieal** [comment]
**ESPNow Gateway** and **Device** firmware are different, will ESPNow Gateway act as an initiator?

Is there any example of downloading firmware via UART?

**Comment by lhespress** [comment]
@andy-danieal 

Yeath, ESP-NOW gateway can store data for OTA.

You can reference the link as follows which is the serial protocol used by the UART:
https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/serial-protocol.html
