### ISSUE TITLE
esp-now门磁 (AEGHB-626)

### ISSUE THREAD

**Issue by 602293544** [espressif/esp-now#118]
请问各位大佬，有没有espnow做门磁的案例，主要是常开和常关这方便的硬件不会做，还得低功耗睡眠或者直接断电

**Comment by lhespress** [comment]
@602293544 门磁是作为发送端还是接收端？能介绍下门磁的通信框图吗？

**Comment by lhespress** [comment]
@602293544 Closing this issue since there has been no update on this. Please feel free to reopen if required.
