### ISSUE TITLE
Remove dependency on UART console input (AEGHB-695)

### ISSUE THREAD

**Issue by sirdeniel** [espressif/esp-now#121]
## Problem
There is an option in ESP-NOW Kconfig that allows to select a UART for console input (UART0 or UART1). However, if a project disables UART console option (sdkconfig: ESP System settings -> Channel for console output: None) it will get compilation errors thinking there is no supported board when it actually is supported
The blame is here:
https://github.com/espressif/esp-now/blob/faea6efa235e8ab9e3b0aa376b748e63bf6106b5/src/debug/src/espnow_console.c#L283

What is the best approach to fix this issue? I could perform a PR to disable it from the ESP-NOW Kconfig directly
Edit: Improve writing

**Comment by lhespress** [comment]
@sirdeniel The `espnow_console.c` is showcasing the console component. If `CONFIG_ESP_CONSOLE_NONE` is enabled, the console is not used so the `espnow_console.c` doesn't make much sense anymore.

**Comment by lhespress** [comment]
@sirdeniel Closing this issue since there has been no update on this. Please feel free to reopen if required.
