### ISSUE TITLE
Decoding "MAC Header" / espnow_frame_head (AEGHB-749)

### ISSUE THREAD

**Issue by ChuckMash** [espressif/esp-now#125]
Hello,

I am trying to decode the MAC Header on the receiving end and I am running into some trouble.

Can you confirm that **uint16_t frame_head;** is the same as **espnow_frame_head_t** ?

https://github.com/espressif/esp-now/blob/master/src/espnow/src/espnow.c#L60

<pre>typedef struct {
    <b>uint16_t frame_head;</b>
    uint16_t duration;
    uint8_t destination_address[6];
    uint8_t source_address[6];
    uint8_t broadcast_address[6];
    uint16_t sequence_control;

    uint8_t category_code;
    uint8_t organization_identifier[3]; // 0x18fe34
    uint8_t random_values[4];
    struct {
        uint8_t element_id;                 // 0xdd
        uint8_t lenght;                     //
        uint8_t organization_identifier[3]; // 0x18fe34
        uint8_t type;                       // 4
        uint8_t version;
        uint8_t body[0];
    } vendor_specific_content;
} __attribute__((packed)) espnow_frame_format_t;
</pre>

https://github.com/espressif/esp-now/blob/master/src/espnow/include/espnow.h#L154
<pre>
typedef struct espnow_frame_head_s {
    uint16_t magic;                    /**< Unique identifier of each packet. Packets with the same identifier will be filtered. 0: a random number */
    uint8_t channel              : 4;  /**< Set the channel where the packet is sent, ESPNOW_CHANNEL_CURRENT or ESPNOW_CHANNEL_ALL */
    bool filter_adjacent_channel : 1;  /**< Because ESP-NOW is sent through HT20, it can receive packets from adjacent channels */
    bool filter_weak_signal      : 1;  /**< When the signal received by the receiving device is lower than forward_rssi, frame_head data will be discarded */
    bool security                : 1;  /**< The payload data is encrypted if security is true */
    uint16_t                     : 4;  /**< Reserved */

    /**
     * @brief Configure broadcast
     */
    bool broadcast              : 1;  /**< Packet sent in broadcast mode or unicast mode */
    bool group                  : 1;  /**< Only the group set as broadcast transmission mode is valid */
    bool ack                    : 1;  /**< Wait for the receiving device to return ack to ensure transmission reliability */
    uint16_t retransmit_count   : 5;  /**< Too many packet retransmissions will lead to network congestion */
    uint8_t forward_ttl         : 5;  /**< Number of hops in data transfer */
    int8_t forward_rssi         : 8;  /**< When the data packet signal received by the receiving device is lower than forward_rssi, it will not be transferred,
                                           in order to avoid network congestion caused by packet transfer */
} ESPNOW_PACKED_STRUCT <b>espnow_frame_head_t</b>;
</pre>

Would it be proper to assume that 
`uint16_t frame_head;` can be changed to `espnow_frame_head_t frame_head` ?

**Comment by lhespress** [comment]
@ChuckMash 
They are different:

- First is the 802.11 frame, which was added to acquire RX control information for compatibility with previous versions and has no longer been employed from ESP-IDF v5.0.1. For detailed information, please refer to the following link:

https://github.com/espressif/esp-now/blob/master/src/espnow/src/espnow.c#L185
https://github.com/espressif/esp-now/blob/master/src/espnow/src/espnow.c#L188

- Second is the application frame, which is defined for handling the data received by ESP-NOW.
