### ISSUE TITLE
Usb ip with two esp32's (AEGHB-801)

### ISSUE THREAD

**Issue by maaamcube** [espressif/esp-now#127]
Hi everyone,
I don't know where i can answer my question because there is no discussion section.
I looking to establish wifi comunication between two esp32's, one connected to a PC to the software and another one to Stm32's(USB device).
Is it possible to send the Stm32's USB's to the PC using the esp now ? like usb ip
Thank's.

**Comment by lhespress** [comment]
@maaamcube PTAL [get-start](https://github.com/espressif/esp-now/tree/master/examples/get-started) example which show two  ESP32 comunication. One device receives data through the serial port and broadcasts it to all nodes through ESP-NOW data. The others will output the data through the serial port when receive the data.

**Comment by lhespress** [comment]
@maaamcube PTAL [usb_wireless_bridge](https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-usb-bridge/examples/usb_wireless_bridge#wireless-mode) solutions.

**Comment by maaamcube** [comment]
@lhespress i can't use usb for the MCU

**Comment by lhespress** [comment]
@maaamcube The struct is as follows, right?
![Struct](https://github.com/user-attachments/assets/d27380b3-28cc-4107-b342-36c92d58ad96)

**Comment by maaamcube** [comment]
@lhespress exactly, only usb, no uart.

**Comment by lhespress** [comment]
@maaamcube  Correct?
![001](https://github.com/user-attachments/assets/7a55fbcb-3480-4e6b-8fb4-fdc6e1de7079)

**Comment by maaamcube** [comment]
@lhespress yes

**Comment by lhespress** [comment]
@maaamcube https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb

**Comment by maaamcube** [comment]
@lhespress it's an example for usb only, there is no wifi.

**Comment by lhespress** [comment]
@maaamcube First, confirm the USB function works fine based on usb example, Then replace UART to USB and confirm the ESP-NOW function works fine based on get-start example.

**Comment by maaamcube** [comment]
@lhespress i tested https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb and https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/host/usb_cdc_basic works fine but i don't know how to replace UART by USB, can you show me what i have to do ?

**Comment by lhespress** [comment]
@maaamcube Please change [app_uart_initialize](https://github.com/espressif/esp-now/blob/master/examples/get-started/main/app_main.c#L66) API to USB.

**Comment by lhespress** [comment]
@maaamcube Closing this issue since there has been no update on this. Please feel free to reopen if required.
