### ISSUE TITLE
Esp 8266 (AEGHB-40)

### ISSUE THREAD

**Issue by renanmbs** [espressif/esp-now#18]
I am trying to have a duplex communication with an esp32 and an esp8266-01.

Is it supported? Or just communications between esp32s?

**Comment by LJYSP** [comment]
ESP8266 supports esp-now basic APIs like in https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/network/esp_now.html. This project is developed based on these basic APIs, but haven't been ported on ESP8266. Refer to the project, you may develop your own esp-now project on ESP8266.

**Comment by lhespress** [comment]
@renanmbs Any update about this?

**Comment by renanmbs** [comment]
I was able to send some bytes to xFFFF, and the esp32 received it. But I wasn’t able to do a duplex communication as I was intending

**Comment by lhespress** [comment]
@renanmbs Thanks for your feedback, i'll check it again.

**Comment by lhespress** [comment]
@renanmbs The master branch of ESP8266 has fix the issue, please update and try again.

**Comment by lhespress** [comment]
@renanmbs Closing this issue since there has been no update on this. Please feel free to reopen if required.
