### ISSUE TITLE
I already have the DEVELOPMENT environment for ESP-IDF. How can I integrate ESP-NOW into the IDF project

### ISSUE THREAD

**Issue by lybgo** [espressif/esp-now#2]
I already have the DEVELOPMENT environment for ESP-IDF. How can I integrate ESP-NOW into the IDF project

**Comment by zhanzhaocheng** [comment]
Add `set(ESPNOW_PATH /path/to/esp-now/)` in `CMakeLists.txt` in your project directory
or 
Add environment variable `export ESPNOW_PATH=/path/to/esp-now/`

**Comment by lybgo** [comment]
I have set ```set(ESPNOW_PATH /path/to/esp-now/)```, but there is an error
![微信截图_20210923114058](https://user-images.githubusercontent.com/3245385/134451875-9f5b17fc-a550-4593-b7ec-da56351d17c6.png)
.
![微信图片_20210923114213](https://user-images.githubusercontent.com/3245385/134451885-0dcc1912-416d-4489-a5ed-1f134a97d901.png)

**Comment by lybgo** [comment]
Need to add more code: ```set(EXTRA_COMPONENT_DIRS ${ESPNOW_PATH}/components)```
