### ISSUE TITLE
Problem with flash hello_world.bin after reset in OTA

### ISSUE THREAD

**Issue by oliverrr97** [espressif/esp-now#20]
I have Problem with flash hello_world.bin after reset in OTA. Responder dont flash hello_world after received
![stiahnutie_odoslanie](https://user-images.githubusercontent.com/98345211/158455774-a3ffbb36-cb66-411d-bb5f-f4905ffd2ace.png)
.
![ERR](https://user-images.githubusercontent.com/98345211/158455855-a50b4226-1af5-4804-a9f1-fc743f9cda68.png)
![HTTP_server](https://user-images.githubusercontent.com/98345211/158455892-c09f2b48-d1a6-401e-a0f9-9c35d8694519.png)

**Comment by LJYSP** [comment]
@oliverrr97  
Please download the hello_word.bin directly in ESP32 and check if it runs OK ?

**Comment by oliverrr97** [comment]
yes, it runs OK.

**Comment by LJYSP** [comment]
@oliverrr97  
I have reproduced the same problem on v4.3.2. We will try to fix it and tell you when it is OK. You may try with v4.3.1 and ota example is tested OK on it .

**Comment by LJYSP** [comment]
@oliverrr97  Please set  “CONFIG_ESPTOOLPY_FLASHFREQ_80M=y” in sdkconfig.default when build  hello_word.bin on ESP32.(For ESP32, the default flash frequency is 40M, For other chip, it is 80M). 
In ota example，the default flash frequency is 80M in sdkconfig.defaults.  The frequency should keep the same.
