### ISSUE TITLE
Problem with debug with write http data (AEGHB-32)

### ISSUE THREAD

**Issue by oliverrr97** [espressif/esp-now#21]
i have problem in example "debug". here is screenshots of my problem.
![image](https://user-images.githubusercontent.com/98345211/159444256-670509c2-5d36-4281-966e-d23b0e7bc7d7.png)
![image](https://user-images.githubusercontent.com/98345211/159444416-3884a85e-5b01-4693-a1e2-1c9118427d19.png)

**Comment by LJYSP** [comment]
@oliverrr97  Please use a TCP testing tool (any third-party TCP testing software) to create a TCP server.

**Comment by oliverrr97** [comment]
I used a testing tool to create an http server, but I still don't know how to enter commands there: help, system_info ...
![image](https://user-images.githubusercontent.com/98345211/160830865-4ff96535-0181-47c5-b96f-3edef069de36.png)

**Comment by LJYSP** [comment]
Please press "enter " in the left console and the output liike this " esp32c3>"
Then input the command "help" and press "enter", the output liike this:
```
esp32c3> help
help 
  Print the list of registered commands

version 
  Get version of chip and SDK
...
```

**Comment by oliverrr97** [comment]
I am not allowed to write anything on the left console. even when I press enter nothing happens. I use the ESP32 DevKitc V4 model.

**Comment by LJYSP** [comment]
What IDF version do you use?

**Comment by oliverrr97** [comment]
I tried it on version 4.3.2 and version 4.4

**Comment by oliverrr97** [comment]
what can i do with it?

**Comment by LJYSP** [comment]
I don't know why, but you can try IDF/example/wifi/iperf example to test if input command is ok. Or change a other ESP32 board to test.

**Comment by lhespress** [comment]
@oliverrr97 Any update about this?

**Comment by lhespress** [comment]
@oliverrr97 Closing this issue since there has been no update on this. Please feel free to reopen if required.
