### ISSUE TITLE
Problem with example control with led_strip.h

### ISSUE THREAD

**Issue by oliverrr97** [espressif/esp-now#22]
I can't find the header file led_strip.h. this header file is neither in the components nor in the esp-idf folder

**Comment by LJYSP** [comment]
Please build with ESP-IDF tag v4.4. That version supports downloading button and led component automatically from  https://staging.components.espressif.tools/search/org:espressif

**Comment by oliverrr97** [comment]
How should I do that

**Comment by oliverrr97** [comment]
I use the development board esp32 devkitc V4, is it possible to demonstrate an example of control on this board?
![image](https://user-images.githubusercontent.com/98345211/159478803-20f42326-50d3-4bc8-9368-dbc3ebbe7bd1.png)
no bind is created when the boot button is pressed two times

**Comment by LJYSP** [comment]
> I use the development board esp32 devkitc V4, is it possible to demonstrate an example of control on this board? ![image](https://user-images.githubusercontent.com/98345211/159478803-20f42326-50d3-4bc8-9368-dbc3ebbe7bd1.png) no bind is created when the boot button is pressed two times

Does this example build with  esp-now v1.0 ？ In that version example, you may press the boot button two times in a short time to bind.
But in your log, it seems it is version before esp-now v1.0 or you add the log?. Anyway, in old version, bind is to press the boot button for more than 1 second.

**Comment by oliverrr97** [comment]
its okey this problem is solved. i have another problem yet with debug.
