### ISSUE TITLE
Problem with wireless_debug

### ISSUE THREAD

**Issue by oliverrr97** [espressif/esp-now#23]
please how do i connect two esp32 devices in this example? how to insert the added pairing code there? is it necessary to insert the added code into both devices? how do you set menucofig? from that tutorial it's not clear to me how to pair two devices.

**Comment by LJYSP** [comment]
You may  not need to connect the two esp32 devices. One device runs the debug example, the other runs this example, and this  example can monitor the debug example device. Please refer to  examples/wireless_debug/README.md.
What is the added pairing code?

**Comment by oliverrr97** [comment]
![image](https://user-images.githubusercontent.com/98345211/162053680-025a5f73-bde9-4239-a840-2ec103e2ad4c.png)
there is a wireless debug device on the left side and a debug device on the right ... the list at the bottom of the left page is displayed after pressing the button to refresh the list on the mobile ... but no device will appear in the list on the mobile

**Comment by lhespress** [comment]
@oliverrr97 Do you try it on master branch and have any update about this?

**Comment by lhespress** [comment]
@oliverrr97 Closing this issue since there has been no update on this. Please feel free to reopen if required.
