### ISSUE TITLE
Example - ota - running on (update) distant esp.

### ISSUE THREAD

**Issue by tan253** [espressif/esp-now#24]
I would like to ask, if there is any way to frequently update distant esp. 
Ota would run on the background and new updates, would be downloaded to it, one after another.

**Comment by LJYSP** [comment]
The new firmware should include ota responder function as follow. When reboot to new image, it can also respond the initiator to update.
```
    espnow_ota_config_t ota_config = {
        .skip_version_check       = true,
        .progress_report_interval = 10,
    };
    espnow_ota_responder_start(&ota_config);
```

**Comment by lhespress** [comment]
@tan253 Any update about this?

**Comment by lhespress** [comment]
@tan253 Closing this issue since there has been no update on this. Please feel free to reopen if required.
