### ISSUE TITLE
Is API in Programming Guide old version of ESP-Now?

### ISSUE THREAD

**Issue by NostalgistL00** [espressif/esp-now#25]
I wanna use esp-now in my little project of ESP8266,i try to find reference in programming guide,and later i saw this.
the API is not the same ,so is this new version of ESP-Now?If so,is there any examples of old version.
Thanks

**Comment by LJYSP** [comment]
This esp-now project is application of esp now, based on the api defined in IDF esp_now.h.  Please refer to IDF/example/wifi/espnow to use the basic esp-now apis.

**Comment by NostalgistL00** [comment]
> 

Thank you.
This helps a lot. :)

**Comment by NostalgistL00** [comment]
> Thank you.
> This helps a lot. :)



> This esp-now project is application of esp now, based on the api defined in IDF esp_now.h. Please refer to IDF/example/wifi/espnow to use the basic esp-now apis.

Thank you.
This helps a lot. :)

**Comment by NostalgistL00** [comment]
> This esp-now project is application of esp now, based on the api defined in IDF esp_now.h. Please refer to IDF/example/wifi/espnow to use the basic esp-now apis.

Thank you.
This helps a lot. :)
