### ISSUE TITLE
Bind Limit of 20 (AEGHB-8)

### ISSUE THREAD

**Issue by tiki30** [espressif/esp-now#28]
Hi, can you explain exactly what limits the pairing of devices to a maximum of 20 ?. If I need to communicate with more than 20 devices without using broadcast, is there a mechanism to do this ?
Many Thanks.

**Comment by LJYSP** [comment]
The WIFI lib and memory cost limit the pairing of devices to a maximum of 20.
If I need to communicate with more than 20 devices without using broadcast, is there a mechanism to do this ?
==> You can add peer address before sending and delete peer address after sending.
```
espnow_add_peer(src_addr, NULL);
espnow_send();
espnow_del_peer(src_addr);
```

**Comment by LJYSP** [comment]
The WIFI lib and memory cost limit the pairing of devices to a maximum of 20.
If I need to communicate with more than 20 devices without using broadcast, is there a mechanism to do this ?
==> You can add peer address before sending and delete peer address after sending.
```
espnow_add_peer(src_addr, NULL);
espnow_send();
espnow_del_peer(src_addr);
```

**Comment by svdrummer** [comment]
If I broadcast would there be a limit. I can set wifi to 15, however, i am switching to esp_now.
I am thinking broadcast is just to one peer FF's in mac.
I dont care about the result of the send

**Comment by lhespress** [comment]
You can ignore the limit of 20 in broadcast mode. We have tested 100 devices as responder which have the max delay timer is 315ms.

**Comment by lhespress** [comment]
@svdrummer Closing this issue since there has been no update on this. Please feel free to reopen if required.
