### ISSUE TITLE
Bind by RSSI example

### ISSUE THREAD

**Issue by poky** [espressif/esp-now#3]
Hi, thank you for the library!
In the promote video shows that the bind is set to within the 4cm RSSI range, could you show where I can find the example of it? 
I'm testing the control example with 3 C3 dev boards, but doesn't show this feature.

Thanks!

![Screen Shot 2021-09-25 at 11 46 15 PM](https://user-images.githubusercontent.com/138415/134777478-8444e824-0220-47db-8124-ff8bbb0cefec.jpg)

**Comment by zhanzhaocheng** [comment]
Currently, the RSSI between the two devices is used as the filter condition for the distance. 

You can modify the filtered data frame through the following configuration (`frame_head.filter_weak_signal`)

```c

                espnow_frame_head_t frame_head = {
                    .retransmit_count = 15,
                    .broadcast        = true,
                    .channel          = ESPNOW_CHANNEL_ALL,
                    .filter_weak_signal = -20,
                };

                espnow_ctrl_data_t data = {
                    .initiator_attribute = ESPNOW_ATTRIBUTE_KEY_1,
                    .responder_attribute = ESPNOW_ATTRIBUTE_POWER,
                    .responder_value_i   = status,
                };

                espnow_ctrl_data_t data = {
                    .initiator_attribute = ESPNOW_ATTRIBUTE_KEY_1,
                    .responder_attribute = ESPNOW_ATTRIBUTE_POWER,
                    .responder_value_i   = status,
                };

                espnow_ctrl_send(ESPNOW_ADDR_BROADCAST, &data, &frame_head, pdMS_TO_TICKS(1000));
```

**Comment by poky** [comment]
Thanks! Will take look for it!

**Comment by poky** [comment]
Hi, when I check the espnow_frame_head_t struct, the data type of filter_weak_signal is boolean?

https://github.com/espressif/esp-now/blob/9db0e7ff03abda6427d5be517d2a4f44eba340d1/components/espnow/include/espnow.h#L127

**Comment by zhanzhaocheng** [comment]
You need to enable filter_weak_signal and set .forward_rssi
![image](https://user-images.githubusercontent.com/19528396/135061247-55606182-f646-4527-a734-8cbcdd3f9775.png)

**Comment by pryhmez** [comment]
hey zhanahaocheng, please you leave a link to an example on how to use this properly
