### ISSUE TITLE
ESP32 【esp_wifi_config_espnow_rate】doesn't work 

### ISSUE THREAD

**Issue by LCreamStarter** [espressif/esp-now#30]
如何配置固定的PHY速率和MCS，esp_wifi_config_espnow_rate不起作用

How to configure PHY rate in WIFI_PHY_RATE_MCS0_LGI, 【esp_wifi_config_espnow_rate 】doesn't work

**Comment by LJYSP** [comment]
@LCreamStarter  是在代码什么位置，如何设置的？
基于 IDF v4.4 ，经测试这样设置是有效的： ESP_ERROR_CHECK(esp_wifi_config_espnow_rate(WIFI_IF_STA, WIFI_PHY_RATE_MCS0_LGI))

**Comment by lhespress** [comment]
@LCreamStarter Any update about this?

**Comment by lhespress** [comment]
@LCreamStarter Closing this issue since there has been no update on this. Please feel free to reopen if required.

**Comment by sywxf** [comment]
esp_wifi_config_espnow_rate(ESPNOW_WIFI_IF,WIFI_PHY_RATE_LORA_500K);提示不支持错误  esp32s3  idf5.0
