### ISSUE TITLE
How to create the continous responder task ??

### ISSUE THREAD

**Issue by horsemann07** [espressif/esp-now#32]
Hello, 

1. I have multiple initiator which initiate initiator task at different times. I want to one responder which respond continuously to every initiator and vice-versa. I tried to create the task which only response but It now working. Can you guys tell me how do i achieve this ?

3. Instead of using the protocomm to create the device private and public for secure connection at run time, I want to use the my own prv and pub key to secure connection. How can I do this??

**Comment by LJYSP** [comment]
1. I am not very clear with your question.

2. There is no api to set own priv and pub key in security handshake. But you can use apis in this file [espnow_security.c] (https://github.com/espressif/esp-now/blob/master/components/security/src/espnow_security.c) to set your own security key directly.
