### ISSUE TITLE
How do I send an ESP networked device like ESP8266 or ESP32 via ESPNOW protocol from my mobile device? (AEGHB-28)

### ISSUE THREAD

**Issue by xiaodeme-aha** [espressif/esp-now#4]
I want to be able to use my cell phone to achieve this kind of light and fast connection to control the device quickly in some places where the network is not good, if I can't use this kind of protocol, is there a protocol that can be paired-free and fast connection can be achieved.

**Comment by zhanzhaocheng** [comment]
For your situation, I recommend that you use BLE for communication. For examples, see: https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/nimble

**Comment by gmag11** [comment]
ESP-NOW can coexist with regular Wi-Fi either AP or STA as soon as you use same channel for both protocols.

**Comment by lhespress** [comment]
@xiaodeme-aha Closing this issue since there has been no update on this. Please feel free to reopen if required.
