### ISSUE TITLE
How to setup in PlatformIO

### ISSUE THREAD

**Issue by brskt-dev** [espressif/esp-now#42]
Hello

I use PlatformIO for my ESP32 
projects, with arduino-espressif32.
I'm trying to find a way to filter Esp Now connections somehow related to signal strength, and then I find this repo...

What I need to understand is how to setup this esp-now repo in my projects, to use the "filter_weak_signal" option!

I hope someone help me :/

**Comment by leeebo** [comment]
HELLO
IM LIBO
I HAVE GOT YOUR LETTER
PLEASE WAIT FOR REPLY

**Comment by LJYSP** [comment]
You can copy `esp-now/components/` to  `esp-idf/components/,`  to use esp-now as components of esp-idf.

**Comment by brskt-dev** [comment]
> You can copy `esp-now/components/` to  `esp-idf/components/,`  to use esp-now as components of esp-idf.

I'll try this, thank u 🙏🏼
