### ISSUE TITLE
Fix the ESPNOW parameters such as seq number and 4-byte random values. (esp_now_send()) (AEGHB-25)

### ISSUE THREAD

**Issue by elmaghba** [espressif/esp-now#46]
Hello,
I hope you are doing well!

I need to fix the seq number and the 4-bytes random values at the  beginning of the payload of ESPNOW packet. I believe that that magic happen in the esp_now_send() function, but I could find any API for that function. (Maybe the esp_now.c)

Is there anyway to access the random_values and sequence_control values in the espnow frame? 

Thank you,
Best regards

**Comment by lhespress** [comment]
@elmaghba Please update to the master branch and check again.

**Comment by lhespress** [comment]
@elmaghba Closing this issue since there has been no update on this. Please feel free to reopen if required.
