### ISSUE TITLE
ESP limit in broadcast (AEGHB-14)

### ISSUE THREAD

**Issue by svdrummer** [espressif/esp-now#50]
In broadcast mode, can I assume the 20 peer limit is not in place? After all, no need to store Ack info and Acks are not sent from any peers other than one from the sender itself(which also sees the broadcast message)

**Comment by lhespress** [comment]
Yes, you can ignore the limit of 20 in broadcast mode. We have tested 100 devices as responder which have the max delay timer is 315ms.
