### ISSUE TITLE
Will this be integrated into IDF?

### ISSUE THREAD

**Issue by gmag11** [espressif/esp-now#6]
It would be really nice that this esp-now improvement is included into IDF. Great work!

**Comment by ljy770** [comment]
This project is an application developed based on IDF , but will not be integrated into IDF.  You can integrated the esp-now/components to your own IDF project.

**Comment by sagar448** [comment]
@ljy770 How can you integrate the ESP-NOW/Components into IDF project? Would it be project level? Or do we drag the components folder into the ESP-NOw folder in the ESP-IDF folder?

**Comment by leeebo** [comment]
HELLO
IM LIBO
I HAVE GOT YOUR LETTER
PLEASE WAIT FOR REPLY

**Comment by LJYSP** [comment]
> @ljy770 How can you integrate the ESP-NOW/Components into IDF project? Would it be project level? Or do we drag the components folder into the ESP-NOw folder in the ESP-IDF folder?
like this: 
cp -r ~/esp-now/components/* esp-idf/components/
cp -r ~/esp-now/examples/* esp-idf/examples/
