### ISSUE TITLE
ESP-NOW sends a data error (AEGHB-127)

### ISSUE THREAD

**Issue by lonelysheep1212** [espressif/esp-now#66]
I want to send some data to another ESP32 by esp_now. But something happenned. As is Followes:
![C3 RY$F$MB%3)4H7U5YA0OH](https://user-images.githubusercontent.com/125008022/229970605-9c5bf27a-348a-4734-a9cb-69ddfe7c8084.png)
![NX2M ~)F2O5$_JCB5 Q1NR6](https://user-images.githubusercontent.com/125008022/229970820-d91e1aff-4c3a-4d13-9b87-8c04d7b8759c.png)

**Comment by svdrummer** [comment]
Try     (uint8_t *) &send_buff,

**Comment by lonelysheep1212** [comment]
Thanks for your feedback, i'll check it again.

**Comment by lhespress** [comment]
@lonelysheep1212 Any update about this?

**Comment by lhespress** [comment]
@lonelysheep1212 Closing this issue since there has been no update on this. Please feel free to reopen if required.
