### ISSUE TITLE
ESPNOW fails because of ESP_ERR_ESPNOW_IF (AEGHB-135)

### ISSUE THREAD

**Issue by lonelysheep1212** [espressif/esp-now#68]
I want to scan the RSSI value of the surrounding device after using wifi, and then send it to the corresponding device through ESPnow, but the program keeps reporting an error.
The programs are as follows：
wifi_init：
![1680938154424](https://user-images.githubusercontent.com/125008022/230708741-8aefa631-41b4-4914-a636-9d9e72606d4e.png)
wifi_scan:
![1680938243117](https://user-images.githubusercontent.com/125008022/230708785-886382b3-54d3-493d-8078-43f34f6962c2.png)
When wifi_scan has done, esp32 got the information,and runs esp_wifi_stop();
wifi init agin:
![1680938440702](https://user-images.githubusercontent.com/125008022/230708933-f62b4d26-972b-4bfe-9870-67c0a4811e5e.png)
esp_now init :
![1680938504580](https://user-images.githubusercontent.com/125008022/230708972-3147ad76-c3e5-48d8-9795-89d53a461108.png)
send data:
![1680938566740](https://user-images.githubusercontent.com/125008022/230709031-fb39bf48-5596-4d9b-b6d0-c0b06e940424.png)
The results are as followed:
![1680938646811](https://user-images.githubusercontent.com/125008022/230709093-6ceb2ee6-3cf1-4e9f-a97b-90f2a2524993.png)
![1680938757261](https://user-images.githubusercontent.com/125008022/230709188-55eaf82a-9718-4615-8781-2d2fb6882324.png)

I don't have a clue about this error, thank you very much if you can help answer it

**Comment by lhespress** [comment]
@lonelysheep1212 It's not necessary runs `esp_wifi_stop()` and `esp_wifi_start()` after got the RSSI info. The error means that current WiFi interface doesn't match that of peer, please check the log as follows before `esp_now_init`:

```
I (3607) wifi:flush txq
I (3607) wifi:stop sw txq
I (3607) wifi:lmac stop hw txq
I (3617) wifi:mode : sta (c8:f0:9e:35:93:70)
I (3617) wifi:enable tsf
I (3617) ESPNOW: espnow [version: 1.0] init
```

**Comment by lonelysheep1212** [comment]
> @lonelysheep1212 It's not necessary runs `esp_wifi_stop()` and `esp_wifi_start()` after got the RSSI info. The error means that current WiFi interface doesn't match that of peer, please check the log as follows before `esp_now_init`:
> 
> ```
> I (3607) wifi:flush txq
> I (3607) wifi:stop sw txq
> I (3607) wifi:lmac stop hw txq
> I (3617) wifi:mode : sta (c8:f0:9e:35:93:70)
> I (3617) wifi:enable tsf
> I (3617) ESPNOW: espnow [version: 1.0] init
> ```
Thanks for your feedback, i'll check it again.

**Comment by lonelysheep1212** [comment]
> 没有必要运行，并且在获得 RSSI 信息后。该错误表示当前WiFi接口与对等方的WiFi接口不匹配，请按以下方式检查日志：`esp_wifi_stop()``esp_wifi_start()``esp_now_init`
> 
> ```
> I (3607) wifi:flush txq
> I (3607) wifi:stop sw txq
> I (3607) wifi:lmac stop hw txq
> I (3617) wifi:mode : sta (c8:f0:9e:35:93:70)
> I (3617) wifi:enable tsf
> I (3617) ESPNOW: espnow [version: 1.0] init
> ```

Thanks for your help， I have solved  problem。
