### ISSUE TITLE
IDF_TARGET in CMake cache does not match IDF_TARGET environment variable. (AEGHB-149)

### ISSUE THREAD

**Issue by lhf-tech** [espressif/esp-now#70]
CMake Error at C:/Users/123/esp/esp-idf/tools/cmake/targets.cmake:19 (message):
  IDF_TARGET in CMake cache does not match IDF_TARGET environment variable.
  To change the target, clear the build directory and sdkconfig file, and
  build the project again
Call Stack (most recent call first):
  C:/Users/Hephi-Lu/esp/esp-idf/tools/cmake/project.cmake:7 (__target_init)
  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!

**Comment by lhespress** [comment]
@lhf-tech Please run "idf.py fullclean" or "rm -rf build/ sdkconfig"

**Comment by lhespress** [comment]
@lhf-tech Closing this issue since there has been no update on this. Please feel free to reopen if required.

**Comment by mstroven-hiviz** [comment]
WHY does the IDF_TARGET variable in CMakeCache.txt keep getting changed?!?!
