### ISSUE TITLE
esp_timesync_check and esp_timesync_wait naming (AEGHB-160)

### ISSUE THREAD

**Issue by grodansparadis** [espressif/esp-now#72]
esp_timesync_check and esp_timesync_wait in espnow_timesync.h  is probably missnamed as they are called espnow_timesync_check and espnow_timesync_wait  in the header file espnow_utils.h

**Comment by lhespress** [comment]
@grodansparadis Thanks for your feedback, i'm sorry for missnamed. Please add the patch as the attachment.
[espnow_timesync.zip](https://github.com/espressif/esp-now/files/11339018/espnow_timesync.zip)

**Comment by grodansparadis** [comment]
@lhespress  No problem here. Just letting you know so it can be corrected.
