### ISSUE TITLE
Checking status of connection  (AEGHB-185)

### ISSUE THREAD

**Issue by pranjul-arctano** [espressif/esp-now#74]
I know it's a connectionless protocol, but is their any other way to know whether the device is connected or not, or to get it's status without continuously sending and receiving messages back and forth.

**Comment by lhespress** [comment]
@pranjul-arctano You can reference the code of [espnow_ctrl](https://github.com/espressif/esp-now/blob/master/src/control/src/espnow_ctrl.c) which will store the MAC for check whether the device can be control or not.

**Comment by lhespress** [comment]
@pranjul-arctano Any update the issue?
