### ISSUE TITLE
 对比 Contrast (AEGHB-232)

### ISSUE THREAD

**Issue by LYL14** [espressif/esp-now#75]
100 devices are networked to send and receive data to the server using espmesh or espnow.Which is better?

**Comment by lhespress** [comment]
@LYL14 Could you detail describe the scenario?

**Comment by wujiangang** [comment]
If your 100 devices want to access the remote cloud directly, it's recommend to use [esp-mesh-lite](https://github.com/espresif/esp-mesh-lite). If only 1 device can access the remote cloud, this device will work as a gateway, and in the local network, it will communicate with other devices by esp-now.

**Comment by lhespress** [comment]
@LYL14  Closing this issue since there has been no update on this. Please feel free to reopen if required.
