### ISSUE TITLE
Are esp_now send/receive APIs thread safe (AEGHB-329)

### ISSUE THREAD

**Issue by M4tsuri** [espressif/esp-now#87]
I wonder if it's safe to

1. call `esp_now_send` in multiple threads
2. call `esp_now_send` in a thread different from where receiving callback is called

Thank you.

**Comment by lhespress** [comment]
@M4tsuri It's safe to call it in multiple threads, you doesn't care the receive callback function, but must wait for the send callback of ```esp_now_send```

**Comment by M4tsuri** [comment]
Got it. Thank you for your prompt reply.

**Comment by M4tsuri** [comment]
Sorry for bothering again. The documentation does not contain thread safety declarations of ESP NOW APIs. May I assume all the APIs are thread safe when not come with a explicit statement about thread safety?
