### ISSUE TITLE
esp-now and ble co-existence  (AEGHB-354)

### ISSUE THREAD

**Issue by NidhinJose** [espressif/esp-now#88]
I am trying to configure a project which uses both ble and esp now for data transferring.I am able to send data using ble but when i try to send data using esp-now, the data is either not getting received at the client side or the data sent from the server side is received at client very late (after 10-15 minutes). Can someone help me to find what the issue is and if there is a way to make both of them work together.

**Comment by lhespress** [comment]
@NidhinJose Could you share your code on the [get-started](https://github.com/espressif/esp-now/tree/master/examples/get-started) example. BTW, pls check whether enable the `CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE` or not.

**Comment by lhespress** [comment]
@NidhinJose Closing this issue since there has been no update on this. Please feel free to reopen if required.
