### ISSUE TITLE
Broadcasting to our own network only

### ISSUE THREAD

**Issue by ankit-thealchemist** [espressif/esp-now#9]
Hello,

I was going through the get started example, just want to know how to broadcast message to out own private group. Suppose I have some devices working on esp now and my neighbour would have some devices working on esp now. How the these two network will be separated? Each network will be able to decode only its netwok messages. 
Thanks!

**Comment by ljy770** [comment]
You can separate the devices by RSSI and set device group by espnow_send_group().

**Comment by ankit-thealchemist** [comment]
@ljy770 Thanks! this sorted out my confusion. Just let me know, when will documentation regarding esp now will be available.
Also just a feature request to also support hash of the password for the authentication.
