### ISSUE TITLE
Error compile 

### ISSUE THREAD

**Issue by ValDect** [espressif/esp-now#90]
I try to compile the project "control "and get
mistake ERROR:
CMake Error at C:/Espressif/Frameworks/esp-idf-4.4.3/tools/cmakebuild.cmake:452
Cannot establish a connection tj the component registry. Are you connected tothe Internet?

**Comment by lhespress** [comment]
@ValDect What do you mean compile the [control](https://github.com/espressif/esp-now/tree/master/examples/control) example? What environment do you work on, Ubuntu, Windows or MacOS?

**Comment by lhespress** [comment]
@ValDect Closing this issue since there has been no update on this. Please feel free to reopen if required.
