### ISSUE TITLE
Please support to ESP32C6 (AEGHB-424)

### ISSUE THREAD

**Issue by DoctorTag** [espressif/esp-now#97]
When we is using esp32c6,this seems to be not supported .

**Comment by lhespress** [comment]
@DoctorTag Please git apply the patch as the attachment and check again.
[support_esp32c6.zip](https://github.com/espressif/esp-now/files/13176876/support_esp32c6.zip)

**Comment by lhespress** [comment]
@DoctorTag Closing this issue since there has been no update on this. Please feel free to reopen if required.
